import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from 'ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _21ff4601 = () => interopDefault(import('..\\pages\\index.vue' /* webpackChunkName: "pages/index" */))
const _7c8c9bfd = () => interopDefault(import('..\\pages\\3D-modeling-and-animation\\index.vue' /* webpackChunkName: "pages/3D-modeling-and-animation/index" */))
const _ae99e474 = () => interopDefault(import('..\\pages\\about\\index.vue' /* webpackChunkName: "pages/about/index" */))
const _62ce42e3 = () => interopDefault(import('..\\pages\\auto-silence-at-prayers-time\\index.vue' /* webpackChunkName: "pages/auto-silence-at-prayers-time/index" */))
const _50fce8c9 = () => interopDefault(import('..\\pages\\blank-page.vue' /* webpackChunkName: "pages/blank-page" */))
const _61d3f45f = () => interopDefault(import('..\\pages\\blog\\index.vue' /* webpackChunkName: "pages/blog/index" */))
const _77fb50e0 = () => interopDefault(import('..\\pages\\codematics-lg-remote-control\\index.vue' /* webpackChunkName: "pages/codematics-lg-remote-control/index" */))
const _6f7622a3 = () => interopDefault(import('..\\pages\\collection\\index.vue' /* webpackChunkName: "pages/collection/index" */))
const _34980513 = () => interopDefault(import('..\\pages\\contact\\index.vue' /* webpackChunkName: "pages/contact/index" */))
const _96651ebc = () => interopDefault(import('..\\pages\\digital-marketing\\index.vue' /* webpackChunkName: "pages/digital-marketing/index" */))
const _6133cb0e = () => interopDefault(import('..\\pages\\flash-on-call-and-sms\\index.vue' /* webpackChunkName: "pages/flash-on-call-and-sms/index" */))
const _7ff0c6e1 = () => interopDefault(import('..\\pages\\game-development\\index.vue' /* webpackChunkName: "pages/game-development/index" */))
const _7d5da058 = () => interopDefault(import('..\\pages\\graphic-designing\\index.vue' /* webpackChunkName: "pages/graphic-designing/index" */))
const _6af62738 = () => interopDefault(import('..\\pages\\guess-the-word-multiplayer\\index.vue' /* webpackChunkName: "pages/guess-the-word-multiplayer/index" */))
const _0497fc5a = () => interopDefault(import('..\\pages\\kardaan-handyman-services-at-your-door-stepearly-access\\index.vue' /* webpackChunkName: "pages/kardaan-handyman-services-at-your-door-stepearly-access/index" */))
const _28b22dd0 = () => interopDefault(import('..\\pages\\login.vue' /* webpackChunkName: "pages/login" */))
const _ae82bac6 = () => interopDefault(import('..\\pages\\mobile-app-development\\index.vue' /* webpackChunkName: "pages/mobile-app-development/index" */))
const _913a95ec = () => interopDefault(import('..\\pages\\privacy-policy\\index.vue' /* webpackChunkName: "pages/privacy-policy/index" */))
const _5a3f0e78 = () => interopDefault(import('..\\pages\\register.vue' /* webpackChunkName: "pages/register" */))
const _e8cd1d76 = () => interopDefault(import('..\\pages\\scam\\index.vue' /* webpackChunkName: "pages/scam/index" */))
const _6571bda3 = () => interopDefault(import('..\\pages\\smart-tvs-remote-control-for-ios-and-android\\index.vue' /* webpackChunkName: "pages/smart-tvs-remote-control-for-ios-and-android/index" */))
const _bf86c388 = () => interopDefault(import('..\\pages\\snap-war\\index.vue' /* webpackChunkName: "pages/snap-war/index" */))
const _738d37a7 = () => interopDefault(import('..\\pages\\sonybravia-android-tv-remote-control\\index.vue' /* webpackChunkName: "pages/sonybravia-android-tv-remote-control/index" */))
const _ca98b3b6 = () => interopDefault(import('..\\pages\\the-blood-community-app\\index.vue' /* webpackChunkName: "pages/the-blood-community-app/index" */))
const _5fd05263 = () => interopDefault(import('..\\pages\\universal-remote-control-for-roku-devices\\index.vue' /* webpackChunkName: "pages/universal-remote-control-for-roku-devices/index" */))
const _d9bb7a58 = () => interopDefault(import('..\\pages\\universal-tv-remote-control\\index.vue' /* webpackChunkName: "pages/universal-tv-remote-control/index" */))
const _0a22aa9e = () => interopDefault(import('..\\pages\\web-development\\index.vue' /* webpackChunkName: "pages/web-development/index" */))
const _a88890ce = () => interopDefault(import('..\\pages\\about\\team.vue' /* webpackChunkName: "pages/about/team" */))
const _49723d6b = () => interopDefault(import('..\\pages\\blog\\detail-blog.vue' /* webpackChunkName: "pages/blog/detail-blog" */))
const _758cd872 = () => interopDefault(import('..\\pages\\collection\\detail-product.vue' /* webpackChunkName: "pages/collection/detail-product" */))
const _11441b23 = () => interopDefault(import('..\\pages\\collection\\products.vue' /* webpackChunkName: "pages/collection/products" */))
const _5cd768a4 = () => interopDefault(import('..\\pages\\contact\\with-map.vue' /* webpackChunkName: "pages/contact/with-map" */))
const _422df997 = () => interopDefault(import('..\\pages\\utils\\coming-soon.vue' /* webpackChunkName: "pages/utils/coming-soon" */))
const _587e7066 = () => interopDefault(import('..\\pages\\utils\\faq.vue' /* webpackChunkName: "pages/utils/faq" */))
const _798059e3 = () => interopDefault(import('..\\pages\\utils\\maintenance.vue' /* webpackChunkName: "pages/utils/maintenance" */))
const _473e1116 = () => interopDefault(import('..\\pages\\utils\\pricing.vue' /* webpackChunkName: "pages/utils/pricing" */))

const emptyFn = () => {}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _21ff4601,
    name: "index___ar"
  }, {
    path: "/de",
    component: _21ff4601,
    name: "index___de"
  }, {
    path: "/en",
    component: _21ff4601,
    name: "index___en"
  }, {
    path: "/id",
    component: _21ff4601,
    name: "index___id"
  }, {
    path: "/pt",
    component: _21ff4601,
    name: "index___pt"
  }, {
    path: "/zh",
    component: _21ff4601,
    name: "index___zh"
  }, {
    path: "/ar/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___ar"
  }, {
    path: "/ar/about",
    component: _ae99e474,
    name: "about___ar"
  }, {
    path: "/ar/auto-silence-at-prayers-time",
    component: _62ce42e3,
    name: "auto-silence-at-prayers-time___ar"
  }, {
    path: "/ar/blank-page",
    component: _50fce8c9,
    name: "blank-page___ar"
  }, {
    path: "/ar/blog",
    component: _61d3f45f,
    name: "blog___ar"
  }, {
    path: "/ar/codematics-lg-remote-control",
    component: _77fb50e0,
    name: "codematics-lg-remote-control___ar"
  }, {
    path: "/ar/collection",
    component: _6f7622a3,
    name: "collection___ar"
  }, {
    path: "/ar/contact",
    component: _34980513,
    name: "contact___ar"
  }, {
    path: "/ar/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___ar"
  }, {
    path: "/ar/flash-on-call-and-sms",
    component: _6133cb0e,
    name: "flash-on-call-and-sms___ar"
  }, {
    path: "/ar/game-development",
    component: _7ff0c6e1,
    name: "game-development___ar"
  }, {
    path: "/ar/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___ar"
  }, {
    path: "/ar/guess-the-word-multiplayer",
    component: _6af62738,
    name: "guess-the-word-multiplayer___ar"
  }, {
    path: "/ar/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _0497fc5a,
    name: "kardaan-handyman-services-at-your-door-stepearly-access___ar"
  }, {
    path: "/ar/login",
    component: _28b22dd0,
    name: "login___ar"
  }, {
    path: "/ar/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___ar"
  }, {
    path: "/ar/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___ar"
  }, {
    path: "/ar/register",
    component: _5a3f0e78,
    name: "register___ar"
  }, {
    path: "/ar/scam",
    component: _e8cd1d76,
    name: "scam___ar"
  }, {
    path: "/ar/smart-tvs-remote-control-for-ios-and-android",
    component: _6571bda3,
    name: "smart-tvs-remote-control-for-ios-and-android___ar"
  }, {
    path: "/ar/snap-war",
    component: _bf86c388,
    name: "snap-war___ar"
  }, {
    path: "/ar/sonybravia-android-tv-remote-control",
    component: _738d37a7,
    name: "sonybravia-android-tv-remote-control___ar"
  }, {
    path: "/ar/the-blood-community-app",
    component: _ca98b3b6,
    name: "the-blood-community-app___ar"
  }, {
    path: "/ar/universal-remote-control-for-roku-devices",
    component: _5fd05263,
    name: "universal-remote-control-for-roku-devices___ar"
  }, {
    path: "/ar/universal-tv-remote-control",
    component: _d9bb7a58,
    name: "universal-tv-remote-control___ar"
  }, {
    path: "/ar/web-development",
    component: _0a22aa9e,
    name: "web-development___ar"
  }, {
    path: "/de/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___de"
  }, {
    path: "/de/about",
    component: _ae99e474,
    name: "about___de"
  }, {
    path: "/de/auto-silence-at-prayers-time",
    component: _62ce42e3,
    name: "auto-silence-at-prayers-time___de"
  }, {
    path: "/de/blank-page",
    component: _50fce8c9,
    name: "blank-page___de"
  }, {
    path: "/de/blog",
    component: _61d3f45f,
    name: "blog___de"
  }, {
    path: "/de/codematics-lg-remote-control",
    component: _77fb50e0,
    name: "codematics-lg-remote-control___de"
  }, {
    path: "/de/collection",
    component: _6f7622a3,
    name: "collection___de"
  }, {
    path: "/de/contact",
    component: _34980513,
    name: "contact___de"
  }, {
    path: "/de/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___de"
  }, {
    path: "/de/flash-on-call-and-sms",
    component: _6133cb0e,
    name: "flash-on-call-and-sms___de"
  }, {
    path: "/de/game-development",
    component: _7ff0c6e1,
    name: "game-development___de"
  }, {
    path: "/de/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___de"
  }, {
    path: "/de/guess-the-word-multiplayer",
    component: _6af62738,
    name: "guess-the-word-multiplayer___de"
  }, {
    path: "/de/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _0497fc5a,
    name: "kardaan-handyman-services-at-your-door-stepearly-access___de"
  }, {
    path: "/de/login",
    component: _28b22dd0,
    name: "login___de"
  }, {
    path: "/de/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___de"
  }, {
    path: "/de/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___de"
  }, {
    path: "/de/register",
    component: _5a3f0e78,
    name: "register___de"
  }, {
    path: "/de/scam",
    component: _e8cd1d76,
    name: "scam___de"
  }, {
    path: "/de/smart-tvs-remote-control-for-ios-and-android",
    component: _6571bda3,
    name: "smart-tvs-remote-control-for-ios-and-android___de"
  }, {
    path: "/de/snap-war",
    component: _bf86c388,
    name: "snap-war___de"
  }, {
    path: "/de/sonybravia-android-tv-remote-control",
    component: _738d37a7,
    name: "sonybravia-android-tv-remote-control___de"
  }, {
    path: "/de/the-blood-community-app",
    component: _ca98b3b6,
    name: "the-blood-community-app___de"
  }, {
    path: "/de/universal-remote-control-for-roku-devices",
    component: _5fd05263,
    name: "universal-remote-control-for-roku-devices___de"
  }, {
    path: "/de/universal-tv-remote-control",
    component: _d9bb7a58,
    name: "universal-tv-remote-control___de"
  }, {
    path: "/de/web-development",
    component: _0a22aa9e,
    name: "web-development___de"
  }, {
    path: "/en/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___en"
  }, {
    path: "/en/about",
    component: _ae99e474,
    name: "about___en"
  }, {
    path: "/en/auto-silence-at-prayers-time",
    component: _62ce42e3,
    name: "auto-silence-at-prayers-time___en"
  }, {
    path: "/en/blank-page",
    component: _50fce8c9,
    name: "blank-page___en"
  }, {
    path: "/en/blog",
    component: _61d3f45f,
    name: "blog___en"
  }, {
    path: "/en/codematics-lg-remote-control",
    component: _77fb50e0,
    name: "codematics-lg-remote-control___en"
  }, {
    path: "/en/collection",
    component: _6f7622a3,
    name: "collection___en"
  }, {
    path: "/en/contact",
    component: _34980513,
    name: "contact___en"
  }, {
    path: "/en/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___en"
  }, {
    path: "/en/flash-on-call-and-sms",
    component: _6133cb0e,
    name: "flash-on-call-and-sms___en"
  }, {
    path: "/en/game-development",
    component: _7ff0c6e1,
    name: "game-development___en"
  }, {
    path: "/en/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___en"
  }, {
    path: "/en/guess-the-word-multiplayer",
    component: _6af62738,
    name: "guess-the-word-multiplayer___en"
  }, {
    path: "/en/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _0497fc5a,
    name: "kardaan-handyman-services-at-your-door-stepearly-access___en"
  }, {
    path: "/en/login",
    component: _28b22dd0,
    name: "login___en"
  }, {
    path: "/en/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___en"
  }, {
    path: "/en/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___en"
  }, {
    path: "/en/register",
    component: _5a3f0e78,
    name: "register___en"
  }, {
    path: "/en/scam",
    component: _e8cd1d76,
    name: "scam___en"
  }, {
    path: "/en/smart-tvs-remote-control-for-ios-and-android",
    component: _6571bda3,
    name: "smart-tvs-remote-control-for-ios-and-android___en"
  }, {
    path: "/en/snap-war",
    component: _bf86c388,
    name: "snap-war___en"
  }, {
    path: "/en/sonybravia-android-tv-remote-control",
    component: _738d37a7,
    name: "sonybravia-android-tv-remote-control___en"
  }, {
    path: "/en/the-blood-community-app",
    component: _ca98b3b6,
    name: "the-blood-community-app___en"
  }, {
    path: "/en/universal-remote-control-for-roku-devices",
    component: _5fd05263,
    name: "universal-remote-control-for-roku-devices___en"
  }, {
    path: "/en/universal-tv-remote-control",
    component: _d9bb7a58,
    name: "universal-tv-remote-control___en"
  }, {
    path: "/en/web-development",
    component: _0a22aa9e,
    name: "web-development___en"
  }, {
    path: "/id/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___id"
  }, {
    path: "/id/about",
    component: _ae99e474,
    name: "about___id"
  }, {
    path: "/id/auto-silence-at-prayers-time",
    component: _62ce42e3,
    name: "auto-silence-at-prayers-time___id"
  }, {
    path: "/id/blank-page",
    component: _50fce8c9,
    name: "blank-page___id"
  }, {
    path: "/id/blog",
    component: _61d3f45f,
    name: "blog___id"
  }, {
    path: "/id/codematics-lg-remote-control",
    component: _77fb50e0,
    name: "codematics-lg-remote-control___id"
  }, {
    path: "/id/collection",
    component: _6f7622a3,
    name: "collection___id"
  }, {
    path: "/id/contact",
    component: _34980513,
    name: "contact___id"
  }, {
    path: "/id/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___id"
  }, {
    path: "/id/flash-on-call-and-sms",
    component: _6133cb0e,
    name: "flash-on-call-and-sms___id"
  }, {
    path: "/id/game-development",
    component: _7ff0c6e1,
    name: "game-development___id"
  }, {
    path: "/id/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___id"
  }, {
    path: "/id/guess-the-word-multiplayer",
    component: _6af62738,
    name: "guess-the-word-multiplayer___id"
  }, {
    path: "/id/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _0497fc5a,
    name: "kardaan-handyman-services-at-your-door-stepearly-access___id"
  }, {
    path: "/id/login",
    component: _28b22dd0,
    name: "login___id"
  }, {
    path: "/id/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___id"
  }, {
    path: "/id/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___id"
  }, {
    path: "/id/register",
    component: _5a3f0e78,
    name: "register___id"
  }, {
    path: "/id/scam",
    component: _e8cd1d76,
    name: "scam___id"
  }, {
    path: "/id/smart-tvs-remote-control-for-ios-and-android",
    component: _6571bda3,
    name: "smart-tvs-remote-control-for-ios-and-android___id"
  }, {
    path: "/id/snap-war",
    component: _bf86c388,
    name: "snap-war___id"
  }, {
    path: "/id/sonybravia-android-tv-remote-control",
    component: _738d37a7,
    name: "sonybravia-android-tv-remote-control___id"
  }, {
    path: "/id/the-blood-community-app",
    component: _ca98b3b6,
    name: "the-blood-community-app___id"
  }, {
    path: "/id/universal-remote-control-for-roku-devices",
    component: _5fd05263,
    name: "universal-remote-control-for-roku-devices___id"
  }, {
    path: "/id/universal-tv-remote-control",
    component: _d9bb7a58,
    name: "universal-tv-remote-control___id"
  }, {
    path: "/id/web-development",
    component: _0a22aa9e,
    name: "web-development___id"
  }, {
    path: "/pt/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___pt"
  }, {
    path: "/pt/about",
    component: _ae99e474,
    name: "about___pt"
  }, {
    path: "/pt/auto-silence-at-prayers-time",
    component: _62ce42e3,
    name: "auto-silence-at-prayers-time___pt"
  }, {
    path: "/pt/blank-page",
    component: _50fce8c9,
    name: "blank-page___pt"
  }, {
    path: "/pt/blog",
    component: _61d3f45f,
    name: "blog___pt"
  }, {
    path: "/pt/codematics-lg-remote-control",
    component: _77fb50e0,
    name: "codematics-lg-remote-control___pt"
  }, {
    path: "/pt/collection",
    component: _6f7622a3,
    name: "collection___pt"
  }, {
    path: "/pt/contact",
    component: _34980513,
    name: "contact___pt"
  }, {
    path: "/pt/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___pt"
  }, {
    path: "/pt/flash-on-call-and-sms",
    component: _6133cb0e,
    name: "flash-on-call-and-sms___pt"
  }, {
    path: "/pt/game-development",
    component: _7ff0c6e1,
    name: "game-development___pt"
  }, {
    path: "/pt/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___pt"
  }, {
    path: "/pt/guess-the-word-multiplayer",
    component: _6af62738,
    name: "guess-the-word-multiplayer___pt"
  }, {
    path: "/pt/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _0497fc5a,
    name: "kardaan-handyman-services-at-your-door-stepearly-access___pt"
  }, {
    path: "/pt/login",
    component: _28b22dd0,
    name: "login___pt"
  }, {
    path: "/pt/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___pt"
  }, {
    path: "/pt/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___pt"
  }, {
    path: "/pt/register",
    component: _5a3f0e78,
    name: "register___pt"
  }, {
    path: "/pt/scam",
    component: _e8cd1d76,
    name: "scam___pt"
  }, {
    path: "/pt/smart-tvs-remote-control-for-ios-and-android",
    component: _6571bda3,
    name: "smart-tvs-remote-control-for-ios-and-android___pt"
  }, {
    path: "/pt/snap-war",
    component: _bf86c388,
    name: "snap-war___pt"
  }, {
    path: "/pt/sonybravia-android-tv-remote-control",
    component: _738d37a7,
    name: "sonybravia-android-tv-remote-control___pt"
  }, {
    path: "/pt/the-blood-community-app",
    component: _ca98b3b6,
    name: "the-blood-community-app___pt"
  }, {
    path: "/pt/universal-remote-control-for-roku-devices",
    component: _5fd05263,
    name: "universal-remote-control-for-roku-devices___pt"
  }, {
    path: "/pt/universal-tv-remote-control",
    component: _d9bb7a58,
    name: "universal-tv-remote-control___pt"
  }, {
    path: "/pt/web-development",
    component: _0a22aa9e,
    name: "web-development___pt"
  }, {
    path: "/zh/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___zh"
  }, {
    path: "/zh/about",
    component: _ae99e474,
    name: "about___zh"
  }, {
    path: "/zh/auto-silence-at-prayers-time",
    component: _62ce42e3,
    name: "auto-silence-at-prayers-time___zh"
  }, {
    path: "/zh/blank-page",
    component: _50fce8c9,
    name: "blank-page___zh"
  }, {
    path: "/zh/blog",
    component: _61d3f45f,
    name: "blog___zh"
  }, {
    path: "/zh/codematics-lg-remote-control",
    component: _77fb50e0,
    name: "codematics-lg-remote-control___zh"
  }, {
    path: "/zh/collection",
    component: _6f7622a3,
    name: "collection___zh"
  }, {
    path: "/zh/contact",
    component: _34980513,
    name: "contact___zh"
  }, {
    path: "/zh/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___zh"
  }, {
    path: "/zh/flash-on-call-and-sms",
    component: _6133cb0e,
    name: "flash-on-call-and-sms___zh"
  }, {
    path: "/zh/game-development",
    component: _7ff0c6e1,
    name: "game-development___zh"
  }, {
    path: "/zh/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___zh"
  }, {
    path: "/zh/guess-the-word-multiplayer",
    component: _6af62738,
    name: "guess-the-word-multiplayer___zh"
  }, {
    path: "/zh/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _0497fc5a,
    name: "kardaan-handyman-services-at-your-door-stepearly-access___zh"
  }, {
    path: "/zh/login",
    component: _28b22dd0,
    name: "login___zh"
  }, {
    path: "/zh/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___zh"
  }, {
    path: "/zh/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___zh"
  }, {
    path: "/zh/register",
    component: _5a3f0e78,
    name: "register___zh"
  }, {
    path: "/zh/scam",
    component: _e8cd1d76,
    name: "scam___zh"
  }, {
    path: "/zh/smart-tvs-remote-control-for-ios-and-android",
    component: _6571bda3,
    name: "smart-tvs-remote-control-for-ios-and-android___zh"
  }, {
    path: "/zh/snap-war",
    component: _bf86c388,
    name: "snap-war___zh"
  }, {
    path: "/zh/sonybravia-android-tv-remote-control",
    component: _738d37a7,
    name: "sonybravia-android-tv-remote-control___zh"
  }, {
    path: "/zh/the-blood-community-app",
    component: _ca98b3b6,
    name: "the-blood-community-app___zh"
  }, {
    path: "/zh/universal-remote-control-for-roku-devices",
    component: _5fd05263,
    name: "universal-remote-control-for-roku-devices___zh"
  }, {
    path: "/zh/universal-tv-remote-control",
    component: _d9bb7a58,
    name: "universal-tv-remote-control___zh"
  }, {
    path: "/zh/web-development",
    component: _0a22aa9e,
    name: "web-development___zh"
  }, {
    path: "/ar/about/team",
    component: _a88890ce,
    name: "about-team___ar"
  }, {
    path: "/ar/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___ar"
  }, {
    path: "/ar/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___ar"
  }, {
    path: "/ar/collection/products",
    component: _11441b23,
    name: "collection-products___ar"
  }, {
    path: "/ar/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___ar"
  }, {
    path: "/ar/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___ar"
  }, {
    path: "/ar/utils/faq",
    component: _587e7066,
    name: "utils-faq___ar"
  }, {
    path: "/ar/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___ar"
  }, {
    path: "/ar/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___ar"
  }, {
    path: "/de/about/team",
    component: _a88890ce,
    name: "about-team___de"
  }, {
    path: "/de/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___de"
  }, {
    path: "/de/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___de"
  }, {
    path: "/de/collection/products",
    component: _11441b23,
    name: "collection-products___de"
  }, {
    path: "/de/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___de"
  }, {
    path: "/de/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___de"
  }, {
    path: "/de/utils/faq",
    component: _587e7066,
    name: "utils-faq___de"
  }, {
    path: "/de/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___de"
  }, {
    path: "/de/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___de"
  }, {
    path: "/en/about/team",
    component: _a88890ce,
    name: "about-team___en"
  }, {
    path: "/en/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___en"
  }, {
    path: "/en/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___en"
  }, {
    path: "/en/collection/products",
    component: _11441b23,
    name: "collection-products___en"
  }, {
    path: "/en/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___en"
  }, {
    path: "/en/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___en"
  }, {
    path: "/en/utils/faq",
    component: _587e7066,
    name: "utils-faq___en"
  }, {
    path: "/en/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___en"
  }, {
    path: "/en/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___en"
  }, {
    path: "/id/about/team",
    component: _a88890ce,
    name: "about-team___id"
  }, {
    path: "/id/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___id"
  }, {
    path: "/id/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___id"
  }, {
    path: "/id/collection/products",
    component: _11441b23,
    name: "collection-products___id"
  }, {
    path: "/id/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___id"
  }, {
    path: "/id/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___id"
  }, {
    path: "/id/utils/faq",
    component: _587e7066,
    name: "utils-faq___id"
  }, {
    path: "/id/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___id"
  }, {
    path: "/id/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___id"
  }, {
    path: "/pt/about/team",
    component: _a88890ce,
    name: "about-team___pt"
  }, {
    path: "/pt/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___pt"
  }, {
    path: "/pt/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___pt"
  }, {
    path: "/pt/collection/products",
    component: _11441b23,
    name: "collection-products___pt"
  }, {
    path: "/pt/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___pt"
  }, {
    path: "/pt/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___pt"
  }, {
    path: "/pt/utils/faq",
    component: _587e7066,
    name: "utils-faq___pt"
  }, {
    path: "/pt/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___pt"
  }, {
    path: "/pt/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___pt"
  }, {
    path: "/zh/about/team",
    component: _a88890ce,
    name: "about-team___zh"
  }, {
    path: "/zh/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___zh"
  }, {
    path: "/zh/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___zh"
  }, {
    path: "/zh/collection/products",
    component: _11441b23,
    name: "collection-products___zh"
  }, {
    path: "/zh/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___zh"
  }, {
    path: "/zh/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___zh"
  }, {
    path: "/zh/utils/faq",
    component: _587e7066,
    name: "utils-faq___zh"
  }, {
    path: "/zh/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___zh"
  }, {
    path: "/zh/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___zh"
  }],

  fallback: false
}

export function createRouter (ssrContext, config) {
  const base = (config._app && config._app.basePath) || routerOptions.base
  const router = new Router({ ...routerOptions, base  })

  // TODO: remove in Nuxt 3
  const originalPush = router.push
  router.push = function push (location, onComplete = emptyFn, onAbort) {
    return originalPush.call(this, location, onComplete, onAbort)
  }

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    return resolve(to, current, append)
  }

  return router
}
