import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from 'ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _21ff4601 = () => interopDefault(import('..\\pages\\index.vue' /* webpackChunkName: "pages/index" */))
const _7c8c9bfd = () => interopDefault(import('..\\pages\\3D-modeling-and-animation\\index.vue' /* webpackChunkName: "pages/3D-modeling-and-animation/index" */))
const _ae99e474 = () => interopDefault(import('..\\pages\\about\\index.vue' /* webpackChunkName: "pages/about/index" */))
const _50fce8c9 = () => interopDefault(import('..\\pages\\blank-page.vue' /* webpackChunkName: "pages/blank-page" */))
const _61d3f45f = () => interopDefault(import('..\\pages\\blog\\index.vue' /* webpackChunkName: "pages/blog/index" */))
const _6f7622a3 = () => interopDefault(import('..\\pages\\collection\\index.vue' /* webpackChunkName: "pages/collection/index" */))
const _34980513 = () => interopDefault(import('..\\pages\\contact\\index.vue' /* webpackChunkName: "pages/contact/index" */))
const _96651ebc = () => interopDefault(import('..\\pages\\digital-marketing\\index.vue' /* webpackChunkName: "pages/digital-marketing/index" */))
const _7ff0c6e1 = () => interopDefault(import('..\\pages\\game-development\\index.vue' /* webpackChunkName: "pages/game-development/index" */))
const _7d5da058 = () => interopDefault(import('..\\pages\\graphic-designing\\index.vue' /* webpackChunkName: "pages/graphic-designing/index" */))
const _28b22dd0 = () => interopDefault(import('..\\pages\\login.vue' /* webpackChunkName: "pages/login" */))
const _ae82bac6 = () => interopDefault(import('..\\pages\\mobile-app-development\\index.vue' /* webpackChunkName: "pages/mobile-app-development/index" */))
const _913a95ec = () => interopDefault(import('..\\pages\\privacy-policy\\index.vue' /* webpackChunkName: "pages/privacy-policy/index" */))
const _5a3f0e78 = () => interopDefault(import('..\\pages\\register.vue' /* webpackChunkName: "pages/register" */))
const _0a22aa9e = () => interopDefault(import('..\\pages\\web-development\\index.vue' /* webpackChunkName: "pages/web-development/index" */))
const _a88890ce = () => interopDefault(import('..\\pages\\about\\team.vue' /* webpackChunkName: "pages/about/team" */))
const _17fb0a2b = () => interopDefault(import('..\\pages\\blog\\blood-community-pakistan\\index.vue' /* webpackChunkName: "pages/blog/blood-community-pakistan/index" */))
const _ceaf288c = () => interopDefault(import('..\\pages\\blog\\blood-donation\\index.vue' /* webpackChunkName: "pages/blog/blood-donation/index" */))
const _a7b2d6f0 = () => interopDefault(import('..\\pages\\blog\\bomb-diffuse\\index.vue' /* webpackChunkName: "pages/blog/bomb-diffuse/index" */))
const _3e6b1fca = () => interopDefault(import('..\\pages\\blog\\bomber-warrior\\index.vue' /* webpackChunkName: "pages/blog/bomber-warrior/index" */))
const _424dad2a = () => interopDefault(import('..\\pages\\blog\\cv-builder-app\\index.vue' /* webpackChunkName: "pages/blog/cv-builder-app/index" */))
const _9d424acc = () => interopDefault(import('..\\pages\\blog\\data-privacy\\index.vue' /* webpackChunkName: "pages/blog/data-privacy/index" */))
const _49723d6b = () => interopDefault(import('..\\pages\\blog\\detail-blog.vue' /* webpackChunkName: "pages/blog/detail-blog" */))
const _033547a8 = () => interopDefault(import('..\\pages\\blog\\flicky-chicky-game\\index.vue' /* webpackChunkName: "pages/blog/flicky-chicky-game/index" */))
const _77d0c87a = () => interopDefault(import('..\\pages\\blog\\foldable-smartphones\\index.vue' /* webpackChunkName: "pages/blog/foldable-smartphones/index" */))
const _73276188 = () => interopDefault(import('..\\pages\\blog\\fund-raising-record-keeping\\index.vue' /* webpackChunkName: "pages/blog/fund-raising-record-keeping/index" */))
const _c545fc5c = () => interopDefault(import('..\\pages\\blog\\remote-control-for-sony-tv\\index.vue' /* webpackChunkName: "pages/blog/remote-control-for-sony-tv/index" */))
const _ed415270 = () => interopDefault(import('..\\pages\\blog\\remote-for-vizio-tv-ios\\index.vue' /* webpackChunkName: "pages/blog/remote-for-vizio-tv-ios/index" */))
const _0f0e2175 = () => interopDefault(import('..\\pages\\blog\\scam-secure-camera\\index.vue' /* webpackChunkName: "pages/blog/scam-secure-camera/index" */))
const _53e4afcb = () => interopDefault(import('..\\pages\\blog\\smart-tvs-remote-control-for-ios-android\\index.vue' /* webpackChunkName: "pages/blog/smart-tvs-remote-control-for-ios-android/index" */))
const _017e2276 = () => interopDefault(import('..\\pages\\blog\\universal-remote-control-for-ruko-devices\\index.vue' /* webpackChunkName: "pages/blog/universal-remote-control-for-ruko-devices/index" */))
const _03fd291e = () => interopDefault(import('..\\pages\\blog\\universal-remote-for-lg-ios\\index.vue' /* webpackChunkName: "pages/blog/universal-remote-for-lg-ios/index" */))
const _6fdb5936 = () => interopDefault(import('..\\pages\\blog\\universal-tv-remote-control\\index.vue' /* webpackChunkName: "pages/blog/universal-tv-remote-control/index" */))
const _cdaf3c62 = () => interopDefault(import('..\\pages\\category\\cyber-security\\index.vue' /* webpackChunkName: "pages/category/cyber-security/index" */))
const _76f9a3d0 = () => interopDefault(import('..\\pages\\category\\games\\index.vue' /* webpackChunkName: "pages/category/games/index" */))
const _c84c01d8 = () => interopDefault(import('..\\pages\\category\\mobile-apps\\index.vue' /* webpackChunkName: "pages/category/mobile-apps/index" */))
const _7c42bf63 = () => interopDefault(import('..\\pages\\category\\smartphones\\index.vue' /* webpackChunkName: "pages/category/smartphones/index" */))
const _9d624014 = () => interopDefault(import('..\\pages\\category\\social\\index.vue' /* webpackChunkName: "pages/category/social/index" */))
const _758cd872 = () => interopDefault(import('..\\pages\\collection\\detail-product.vue' /* webpackChunkName: "pages/collection/detail-product" */))
const _11441b23 = () => interopDefault(import('..\\pages\\collection\\products.vue' /* webpackChunkName: "pages/collection/products" */))
const _5cd768a4 = () => interopDefault(import('..\\pages\\contact\\with-map.vue' /* webpackChunkName: "pages/contact/with-map" */))
const _66dc84a8 = () => interopDefault(import('..\\pages\\mobile-apps\\remote-control-for-roku-devices\\index.vue' /* webpackChunkName: "pages/mobile-apps/remote-control-for-roku-devices/index" */))
const _e5f337e6 = () => interopDefault(import('..\\pages\\portfolio\\auto-silence-at-prayers-time\\index.vue' /* webpackChunkName: "pages/portfolio/auto-silence-at-prayers-time/index" */))
const _bb991bec = () => interopDefault(import('..\\pages\\portfolio\\codematics-lg-remote-control\\index.vue' /* webpackChunkName: "pages/portfolio/codematics-lg-remote-control/index" */))
const _67384524 = () => interopDefault(import('..\\pages\\portfolio\\flash-on-call-and-sms\\index.vue' /* webpackChunkName: "pages/portfolio/flash-on-call-and-sms/index" */))
const _478eea3c = () => interopDefault(import('..\\pages\\portfolio\\guess-the-word-multiplayer\\index.vue' /* webpackChunkName: "pages/portfolio/guess-the-word-multiplayer/index" */))
const _b68b132e = () => interopDefault(import('..\\pages\\portfolio\\kardaan-handyman-services-at-your-door-stepearly-access\\index.vue' /* webpackChunkName: "pages/portfolio/kardaan-handyman-services-at-your-door-stepearly-access/index" */))
const _509c1f22 = () => interopDefault(import('..\\pages\\portfolio\\scam\\index.vue' /* webpackChunkName: "pages/portfolio/scam/index" */))
const _41264acd = () => interopDefault(import('..\\pages\\portfolio\\smart-tvs-remote-control-for-ios-and-android\\index.vue' /* webpackChunkName: "pages/portfolio/smart-tvs-remote-control-for-ios-and-android/index" */))
const _204d7866 = () => interopDefault(import('..\\pages\\portfolio\\snap-war\\index.vue' /* webpackChunkName: "pages/portfolio/snap-war/index" */))
const _0b4e8ed1 = () => interopDefault(import('..\\pages\\portfolio\\sonybravia-android-tv-remote-control\\index.vue' /* webpackChunkName: "pages/portfolio/sonybravia-android-tv-remote-control/index" */))
const _3181f2bb = () => interopDefault(import('..\\pages\\portfolio\\the-blood-community-app\\index.vue' /* webpackChunkName: "pages/portfolio/the-blood-community-app/index" */))
const _4a2c546a = () => interopDefault(import('..\\pages\\portfolio\\universal-tv-remote-control\\index.vue' /* webpackChunkName: "pages/portfolio/universal-tv-remote-control/index" */))
const _422df997 = () => interopDefault(import('..\\pages\\utils\\coming-soon.vue' /* webpackChunkName: "pages/utils/coming-soon" */))
const _587e7066 = () => interopDefault(import('..\\pages\\utils\\faq.vue' /* webpackChunkName: "pages/utils/faq" */))
const _798059e3 = () => interopDefault(import('..\\pages\\utils\\maintenance.vue' /* webpackChunkName: "pages/utils/maintenance" */))
const _473e1116 = () => interopDefault(import('..\\pages\\utils\\pricing.vue' /* webpackChunkName: "pages/utils/pricing" */))

const emptyFn = () => {}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _21ff4601,
    name: "index___ar"
  }, {
    path: "/de",
    component: _21ff4601,
    name: "index___de"
  }, {
    path: "/en",
    component: _21ff4601,
    name: "index___en"
  }, {
    path: "/id",
    component: _21ff4601,
    name: "index___id"
  }, {
    path: "/pt",
    component: _21ff4601,
    name: "index___pt"
  }, {
    path: "/zh",
    component: _21ff4601,
    name: "index___zh"
  }, {
    path: "/ar/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___ar"
  }, {
    path: "/ar/about",
    component: _ae99e474,
    name: "about___ar"
  }, {
    path: "/ar/blank-page",
    component: _50fce8c9,
    name: "blank-page___ar"
  }, {
    path: "/ar/blog",
    component: _61d3f45f,
    name: "blog___ar"
  }, {
    path: "/ar/collection",
    component: _6f7622a3,
    name: "collection___ar"
  }, {
    path: "/ar/contact",
    component: _34980513,
    name: "contact___ar"
  }, {
    path: "/ar/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___ar"
  }, {
    path: "/ar/game-development",
    component: _7ff0c6e1,
    name: "game-development___ar"
  }, {
    path: "/ar/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___ar"
  }, {
    path: "/ar/login",
    component: _28b22dd0,
    name: "login___ar"
  }, {
    path: "/ar/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___ar"
  }, {
    path: "/ar/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___ar"
  }, {
    path: "/ar/register",
    component: _5a3f0e78,
    name: "register___ar"
  }, {
    path: "/ar/web-development",
    component: _0a22aa9e,
    name: "web-development___ar"
  }, {
    path: "/de/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___de"
  }, {
    path: "/de/about",
    component: _ae99e474,
    name: "about___de"
  }, {
    path: "/de/blank-page",
    component: _50fce8c9,
    name: "blank-page___de"
  }, {
    path: "/de/blog",
    component: _61d3f45f,
    name: "blog___de"
  }, {
    path: "/de/collection",
    component: _6f7622a3,
    name: "collection___de"
  }, {
    path: "/de/contact",
    component: _34980513,
    name: "contact___de"
  }, {
    path: "/de/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___de"
  }, {
    path: "/de/game-development",
    component: _7ff0c6e1,
    name: "game-development___de"
  }, {
    path: "/de/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___de"
  }, {
    path: "/de/login",
    component: _28b22dd0,
    name: "login___de"
  }, {
    path: "/de/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___de"
  }, {
    path: "/de/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___de"
  }, {
    path: "/de/register",
    component: _5a3f0e78,
    name: "register___de"
  }, {
    path: "/de/web-development",
    component: _0a22aa9e,
    name: "web-development___de"
  }, {
    path: "/en/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___en"
  }, {
    path: "/en/about",
    component: _ae99e474,
    name: "about___en"
  }, {
    path: "/en/blank-page",
    component: _50fce8c9,
    name: "blank-page___en"
  }, {
    path: "/en/blog",
    component: _61d3f45f,
    name: "blog___en"
  }, {
    path: "/en/collection",
    component: _6f7622a3,
    name: "collection___en"
  }, {
    path: "/en/contact",
    component: _34980513,
    name: "contact___en"
  }, {
    path: "/en/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___en"
  }, {
    path: "/en/game-development",
    component: _7ff0c6e1,
    name: "game-development___en"
  }, {
    path: "/en/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___en"
  }, {
    path: "/en/login",
    component: _28b22dd0,
    name: "login___en"
  }, {
    path: "/en/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___en"
  }, {
    path: "/en/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___en"
  }, {
    path: "/en/register",
    component: _5a3f0e78,
    name: "register___en"
  }, {
    path: "/en/web-development",
    component: _0a22aa9e,
    name: "web-development___en"
  }, {
    path: "/id/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___id"
  }, {
    path: "/id/about",
    component: _ae99e474,
    name: "about___id"
  }, {
    path: "/id/blank-page",
    component: _50fce8c9,
    name: "blank-page___id"
  }, {
    path: "/id/blog",
    component: _61d3f45f,
    name: "blog___id"
  }, {
    path: "/id/collection",
    component: _6f7622a3,
    name: "collection___id"
  }, {
    path: "/id/contact",
    component: _34980513,
    name: "contact___id"
  }, {
    path: "/id/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___id"
  }, {
    path: "/id/game-development",
    component: _7ff0c6e1,
    name: "game-development___id"
  }, {
    path: "/id/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___id"
  }, {
    path: "/id/login",
    component: _28b22dd0,
    name: "login___id"
  }, {
    path: "/id/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___id"
  }, {
    path: "/id/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___id"
  }, {
    path: "/id/register",
    component: _5a3f0e78,
    name: "register___id"
  }, {
    path: "/id/web-development",
    component: _0a22aa9e,
    name: "web-development___id"
  }, {
    path: "/pt/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___pt"
  }, {
    path: "/pt/about",
    component: _ae99e474,
    name: "about___pt"
  }, {
    path: "/pt/blank-page",
    component: _50fce8c9,
    name: "blank-page___pt"
  }, {
    path: "/pt/blog",
    component: _61d3f45f,
    name: "blog___pt"
  }, {
    path: "/pt/collection",
    component: _6f7622a3,
    name: "collection___pt"
  }, {
    path: "/pt/contact",
    component: _34980513,
    name: "contact___pt"
  }, {
    path: "/pt/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___pt"
  }, {
    path: "/pt/game-development",
    component: _7ff0c6e1,
    name: "game-development___pt"
  }, {
    path: "/pt/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___pt"
  }, {
    path: "/pt/login",
    component: _28b22dd0,
    name: "login___pt"
  }, {
    path: "/pt/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___pt"
  }, {
    path: "/pt/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___pt"
  }, {
    path: "/pt/register",
    component: _5a3f0e78,
    name: "register___pt"
  }, {
    path: "/pt/web-development",
    component: _0a22aa9e,
    name: "web-development___pt"
  }, {
    path: "/zh/3D-modeling-and-animation",
    component: _7c8c9bfd,
    name: "3D-modeling-and-animation___zh"
  }, {
    path: "/zh/about",
    component: _ae99e474,
    name: "about___zh"
  }, {
    path: "/zh/blank-page",
    component: _50fce8c9,
    name: "blank-page___zh"
  }, {
    path: "/zh/blog",
    component: _61d3f45f,
    name: "blog___zh"
  }, {
    path: "/zh/collection",
    component: _6f7622a3,
    name: "collection___zh"
  }, {
    path: "/zh/contact",
    component: _34980513,
    name: "contact___zh"
  }, {
    path: "/zh/digital-marketing",
    component: _96651ebc,
    name: "digital-marketing___zh"
  }, {
    path: "/zh/game-development",
    component: _7ff0c6e1,
    name: "game-development___zh"
  }, {
    path: "/zh/graphic-designing",
    component: _7d5da058,
    name: "graphic-designing___zh"
  }, {
    path: "/zh/login",
    component: _28b22dd0,
    name: "login___zh"
  }, {
    path: "/zh/mobile-app-development",
    component: _ae82bac6,
    name: "mobile-app-development___zh"
  }, {
    path: "/zh/privacy-policy",
    component: _913a95ec,
    name: "privacy-policy___zh"
  }, {
    path: "/zh/register",
    component: _5a3f0e78,
    name: "register___zh"
  }, {
    path: "/zh/web-development",
    component: _0a22aa9e,
    name: "web-development___zh"
  }, {
    path: "/ar/about/team",
    component: _a88890ce,
    name: "about-team___ar"
  }, {
    path: "/ar/blog/blood-community-pakistan",
    component: _17fb0a2b,
    name: "blog-blood-community-pakistan___ar"
  }, {
    path: "/ar/blog/blood-donation",
    component: _ceaf288c,
    name: "blog-blood-donation___ar"
  }, {
    path: "/ar/blog/bomb-diffuse",
    component: _a7b2d6f0,
    name: "blog-bomb-diffuse___ar"
  }, {
    path: "/ar/blog/bomber-warrior",
    component: _3e6b1fca,
    name: "blog-bomber-warrior___ar"
  }, {
    path: "/ar/blog/cv-builder-app",
    component: _424dad2a,
    name: "blog-cv-builder-app___ar"
  }, {
    path: "/ar/blog/data-privacy",
    component: _9d424acc,
    name: "blog-data-privacy___ar"
  }, {
    path: "/ar/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___ar"
  }, {
    path: "/ar/blog/flicky-chicky-game",
    component: _033547a8,
    name: "blog-flicky-chicky-game___ar"
  }, {
    path: "/ar/blog/foldable-smartphones",
    component: _77d0c87a,
    name: "blog-foldable-smartphones___ar"
  }, {
    path: "/ar/blog/fund-raising-record-keeping",
    component: _73276188,
    name: "blog-fund-raising-record-keeping___ar"
  }, {
    path: "/ar/blog/remote-control-for-sony-tv",
    component: _c545fc5c,
    name: "blog-remote-control-for-sony-tv___ar"
  }, {
    path: "/ar/blog/remote-for-vizio-tv-ios",
    component: _ed415270,
    name: "blog-remote-for-vizio-tv-ios___ar"
  }, {
    path: "/ar/blog/scam-secure-camera",
    component: _0f0e2175,
    name: "blog-scam-secure-camera___ar"
  }, {
    path: "/ar/blog/smart-tvs-remote-control-for-ios-android",
    component: _53e4afcb,
    name: "blog-smart-tvs-remote-control-for-ios-android___ar"
  }, {
    path: "/ar/blog/universal-remote-control-for-ruko-devices",
    component: _017e2276,
    name: "blog-universal-remote-control-for-ruko-devices___ar"
  }, {
    path: "/ar/blog/universal-remote-for-lg-ios",
    component: _03fd291e,
    name: "blog-universal-remote-for-lg-ios___ar"
  }, {
    path: "/ar/blog/universal-tv-remote-control",
    component: _6fdb5936,
    name: "blog-universal-tv-remote-control___ar"
  }, {
    path: "/ar/category/cyber-security",
    component: _cdaf3c62,
    name: "category-cyber-security___ar"
  }, {
    path: "/ar/category/games",
    component: _76f9a3d0,
    name: "category-games___ar"
  }, {
    path: "/ar/category/mobile-apps",
    component: _c84c01d8,
    name: "category-mobile-apps___ar"
  }, {
    path: "/ar/category/smartphones",
    component: _7c42bf63,
    name: "category-smartphones___ar"
  }, {
    path: "/ar/category/social",
    component: _9d624014,
    name: "category-social___ar"
  }, {
    path: "/ar/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___ar"
  }, {
    path: "/ar/collection/products",
    component: _11441b23,
    name: "collection-products___ar"
  }, {
    path: "/ar/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___ar"
  }, {
    path: "/ar/mobile-apps/remote-control-for-roku-devices",
    component: _66dc84a8,
    name: "mobile-apps-remote-control-for-roku-devices___ar"
  }, {
    path: "/ar/portfolio/auto-silence-at-prayers-time",
    component: _e5f337e6,
    name: "portfolio-auto-silence-at-prayers-time___ar"
  }, {
    path: "/ar/portfolio/codematics-lg-remote-control",
    component: _bb991bec,
    name: "portfolio-codematics-lg-remote-control___ar"
  }, {
    path: "/ar/portfolio/flash-on-call-and-sms",
    component: _67384524,
    name: "portfolio-flash-on-call-and-sms___ar"
  }, {
    path: "/ar/portfolio/guess-the-word-multiplayer",
    component: _478eea3c,
    name: "portfolio-guess-the-word-multiplayer___ar"
  }, {
    path: "/ar/portfolio/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _b68b132e,
    name: "portfolio-kardaan-handyman-services-at-your-door-stepearly-access___ar"
  }, {
    path: "/ar/portfolio/scam",
    component: _509c1f22,
    name: "portfolio-scam___ar"
  }, {
    path: "/ar/portfolio/smart-tvs-remote-control-for-ios-and-android",
    component: _41264acd,
    name: "portfolio-smart-tvs-remote-control-for-ios-and-android___ar"
  }, {
    path: "/ar/portfolio/snap-war",
    component: _204d7866,
    name: "portfolio-snap-war___ar"
  }, {
    path: "/ar/portfolio/sonybravia-android-tv-remote-control",
    component: _0b4e8ed1,
    name: "portfolio-sonybravia-android-tv-remote-control___ar"
  }, {
    path: "/ar/portfolio/the-blood-community-app",
    component: _3181f2bb,
    name: "portfolio-the-blood-community-app___ar"
  }, {
    path: "/ar/portfolio/universal-tv-remote-control",
    component: _4a2c546a,
    name: "portfolio-universal-tv-remote-control___ar"
  }, {
    path: "/ar/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___ar"
  }, {
    path: "/ar/utils/faq",
    component: _587e7066,
    name: "utils-faq___ar"
  }, {
    path: "/ar/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___ar"
  }, {
    path: "/ar/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___ar"
  }, {
    path: "/de/about/team",
    component: _a88890ce,
    name: "about-team___de"
  }, {
    path: "/de/blog/blood-community-pakistan",
    component: _17fb0a2b,
    name: "blog-blood-community-pakistan___de"
  }, {
    path: "/de/blog/blood-donation",
    component: _ceaf288c,
    name: "blog-blood-donation___de"
  }, {
    path: "/de/blog/bomb-diffuse",
    component: _a7b2d6f0,
    name: "blog-bomb-diffuse___de"
  }, {
    path: "/de/blog/bomber-warrior",
    component: _3e6b1fca,
    name: "blog-bomber-warrior___de"
  }, {
    path: "/de/blog/cv-builder-app",
    component: _424dad2a,
    name: "blog-cv-builder-app___de"
  }, {
    path: "/de/blog/data-privacy",
    component: _9d424acc,
    name: "blog-data-privacy___de"
  }, {
    path: "/de/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___de"
  }, {
    path: "/de/blog/flicky-chicky-game",
    component: _033547a8,
    name: "blog-flicky-chicky-game___de"
  }, {
    path: "/de/blog/foldable-smartphones",
    component: _77d0c87a,
    name: "blog-foldable-smartphones___de"
  }, {
    path: "/de/blog/fund-raising-record-keeping",
    component: _73276188,
    name: "blog-fund-raising-record-keeping___de"
  }, {
    path: "/de/blog/remote-control-for-sony-tv",
    component: _c545fc5c,
    name: "blog-remote-control-for-sony-tv___de"
  }, {
    path: "/de/blog/remote-for-vizio-tv-ios",
    component: _ed415270,
    name: "blog-remote-for-vizio-tv-ios___de"
  }, {
    path: "/de/blog/scam-secure-camera",
    component: _0f0e2175,
    name: "blog-scam-secure-camera___de"
  }, {
    path: "/de/blog/smart-tvs-remote-control-for-ios-android",
    component: _53e4afcb,
    name: "blog-smart-tvs-remote-control-for-ios-android___de"
  }, {
    path: "/de/blog/universal-remote-control-for-ruko-devices",
    component: _017e2276,
    name: "blog-universal-remote-control-for-ruko-devices___de"
  }, {
    path: "/de/blog/universal-remote-for-lg-ios",
    component: _03fd291e,
    name: "blog-universal-remote-for-lg-ios___de"
  }, {
    path: "/de/blog/universal-tv-remote-control",
    component: _6fdb5936,
    name: "blog-universal-tv-remote-control___de"
  }, {
    path: "/de/category/cyber-security",
    component: _cdaf3c62,
    name: "category-cyber-security___de"
  }, {
    path: "/de/category/games",
    component: _76f9a3d0,
    name: "category-games___de"
  }, {
    path: "/de/category/mobile-apps",
    component: _c84c01d8,
    name: "category-mobile-apps___de"
  }, {
    path: "/de/category/smartphones",
    component: _7c42bf63,
    name: "category-smartphones___de"
  }, {
    path: "/de/category/social",
    component: _9d624014,
    name: "category-social___de"
  }, {
    path: "/de/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___de"
  }, {
    path: "/de/collection/products",
    component: _11441b23,
    name: "collection-products___de"
  }, {
    path: "/de/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___de"
  }, {
    path: "/de/mobile-apps/remote-control-for-roku-devices",
    component: _66dc84a8,
    name: "mobile-apps-remote-control-for-roku-devices___de"
  }, {
    path: "/de/portfolio/auto-silence-at-prayers-time",
    component: _e5f337e6,
    name: "portfolio-auto-silence-at-prayers-time___de"
  }, {
    path: "/de/portfolio/codematics-lg-remote-control",
    component: _bb991bec,
    name: "portfolio-codematics-lg-remote-control___de"
  }, {
    path: "/de/portfolio/flash-on-call-and-sms",
    component: _67384524,
    name: "portfolio-flash-on-call-and-sms___de"
  }, {
    path: "/de/portfolio/guess-the-word-multiplayer",
    component: _478eea3c,
    name: "portfolio-guess-the-word-multiplayer___de"
  }, {
    path: "/de/portfolio/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _b68b132e,
    name: "portfolio-kardaan-handyman-services-at-your-door-stepearly-access___de"
  }, {
    path: "/de/portfolio/scam",
    component: _509c1f22,
    name: "portfolio-scam___de"
  }, {
    path: "/de/portfolio/smart-tvs-remote-control-for-ios-and-android",
    component: _41264acd,
    name: "portfolio-smart-tvs-remote-control-for-ios-and-android___de"
  }, {
    path: "/de/portfolio/snap-war",
    component: _204d7866,
    name: "portfolio-snap-war___de"
  }, {
    path: "/de/portfolio/sonybravia-android-tv-remote-control",
    component: _0b4e8ed1,
    name: "portfolio-sonybravia-android-tv-remote-control___de"
  }, {
    path: "/de/portfolio/the-blood-community-app",
    component: _3181f2bb,
    name: "portfolio-the-blood-community-app___de"
  }, {
    path: "/de/portfolio/universal-tv-remote-control",
    component: _4a2c546a,
    name: "portfolio-universal-tv-remote-control___de"
  }, {
    path: "/de/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___de"
  }, {
    path: "/de/utils/faq",
    component: _587e7066,
    name: "utils-faq___de"
  }, {
    path: "/de/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___de"
  }, {
    path: "/de/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___de"
  }, {
    path: "/en/about/team",
    component: _a88890ce,
    name: "about-team___en"
  }, {
    path: "/en/blog/blood-community-pakistan",
    component: _17fb0a2b,
    name: "blog-blood-community-pakistan___en"
  }, {
    path: "/en/blog/blood-donation",
    component: _ceaf288c,
    name: "blog-blood-donation___en"
  }, {
    path: "/en/blog/bomb-diffuse",
    component: _a7b2d6f0,
    name: "blog-bomb-diffuse___en"
  }, {
    path: "/en/blog/bomber-warrior",
    component: _3e6b1fca,
    name: "blog-bomber-warrior___en"
  }, {
    path: "/en/blog/cv-builder-app",
    component: _424dad2a,
    name: "blog-cv-builder-app___en"
  }, {
    path: "/en/blog/data-privacy",
    component: _9d424acc,
    name: "blog-data-privacy___en"
  }, {
    path: "/en/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___en"
  }, {
    path: "/en/blog/flicky-chicky-game",
    component: _033547a8,
    name: "blog-flicky-chicky-game___en"
  }, {
    path: "/en/blog/foldable-smartphones",
    component: _77d0c87a,
    name: "blog-foldable-smartphones___en"
  }, {
    path: "/en/blog/fund-raising-record-keeping",
    component: _73276188,
    name: "blog-fund-raising-record-keeping___en"
  }, {
    path: "/en/blog/remote-control-for-sony-tv",
    component: _c545fc5c,
    name: "blog-remote-control-for-sony-tv___en"
  }, {
    path: "/en/blog/remote-for-vizio-tv-ios",
    component: _ed415270,
    name: "blog-remote-for-vizio-tv-ios___en"
  }, {
    path: "/en/blog/scam-secure-camera",
    component: _0f0e2175,
    name: "blog-scam-secure-camera___en"
  }, {
    path: "/en/blog/smart-tvs-remote-control-for-ios-android",
    component: _53e4afcb,
    name: "blog-smart-tvs-remote-control-for-ios-android___en"
  }, {
    path: "/en/blog/universal-remote-control-for-ruko-devices",
    component: _017e2276,
    name: "blog-universal-remote-control-for-ruko-devices___en"
  }, {
    path: "/en/blog/universal-remote-for-lg-ios",
    component: _03fd291e,
    name: "blog-universal-remote-for-lg-ios___en"
  }, {
    path: "/en/blog/universal-tv-remote-control",
    component: _6fdb5936,
    name: "blog-universal-tv-remote-control___en"
  }, {
    path: "/en/category/cyber-security",
    component: _cdaf3c62,
    name: "category-cyber-security___en"
  }, {
    path: "/en/category/games",
    component: _76f9a3d0,
    name: "category-games___en"
  }, {
    path: "/en/category/mobile-apps",
    component: _c84c01d8,
    name: "category-mobile-apps___en"
  }, {
    path: "/en/category/smartphones",
    component: _7c42bf63,
    name: "category-smartphones___en"
  }, {
    path: "/en/category/social",
    component: _9d624014,
    name: "category-social___en"
  }, {
    path: "/en/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___en"
  }, {
    path: "/en/collection/products",
    component: _11441b23,
    name: "collection-products___en"
  }, {
    path: "/en/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___en"
  }, {
    path: "/en/mobile-apps/remote-control-for-roku-devices",
    component: _66dc84a8,
    name: "mobile-apps-remote-control-for-roku-devices___en"
  }, {
    path: "/en/portfolio/auto-silence-at-prayers-time",
    component: _e5f337e6,
    name: "portfolio-auto-silence-at-prayers-time___en"
  }, {
    path: "/en/portfolio/codematics-lg-remote-control",
    component: _bb991bec,
    name: "portfolio-codematics-lg-remote-control___en"
  }, {
    path: "/en/portfolio/flash-on-call-and-sms",
    component: _67384524,
    name: "portfolio-flash-on-call-and-sms___en"
  }, {
    path: "/en/portfolio/guess-the-word-multiplayer",
    component: _478eea3c,
    name: "portfolio-guess-the-word-multiplayer___en"
  }, {
    path: "/en/portfolio/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _b68b132e,
    name: "portfolio-kardaan-handyman-services-at-your-door-stepearly-access___en"
  }, {
    path: "/en/portfolio/scam",
    component: _509c1f22,
    name: "portfolio-scam___en"
  }, {
    path: "/en/portfolio/smart-tvs-remote-control-for-ios-and-android",
    component: _41264acd,
    name: "portfolio-smart-tvs-remote-control-for-ios-and-android___en"
  }, {
    path: "/en/portfolio/snap-war",
    component: _204d7866,
    name: "portfolio-snap-war___en"
  }, {
    path: "/en/portfolio/sonybravia-android-tv-remote-control",
    component: _0b4e8ed1,
    name: "portfolio-sonybravia-android-tv-remote-control___en"
  }, {
    path: "/en/portfolio/the-blood-community-app",
    component: _3181f2bb,
    name: "portfolio-the-blood-community-app___en"
  }, {
    path: "/en/portfolio/universal-tv-remote-control",
    component: _4a2c546a,
    name: "portfolio-universal-tv-remote-control___en"
  }, {
    path: "/en/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___en"
  }, {
    path: "/en/utils/faq",
    component: _587e7066,
    name: "utils-faq___en"
  }, {
    path: "/en/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___en"
  }, {
    path: "/en/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___en"
  }, {
    path: "/id/about/team",
    component: _a88890ce,
    name: "about-team___id"
  }, {
    path: "/id/blog/blood-community-pakistan",
    component: _17fb0a2b,
    name: "blog-blood-community-pakistan___id"
  }, {
    path: "/id/blog/blood-donation",
    component: _ceaf288c,
    name: "blog-blood-donation___id"
  }, {
    path: "/id/blog/bomb-diffuse",
    component: _a7b2d6f0,
    name: "blog-bomb-diffuse___id"
  }, {
    path: "/id/blog/bomber-warrior",
    component: _3e6b1fca,
    name: "blog-bomber-warrior___id"
  }, {
    path: "/id/blog/cv-builder-app",
    component: _424dad2a,
    name: "blog-cv-builder-app___id"
  }, {
    path: "/id/blog/data-privacy",
    component: _9d424acc,
    name: "blog-data-privacy___id"
  }, {
    path: "/id/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___id"
  }, {
    path: "/id/blog/flicky-chicky-game",
    component: _033547a8,
    name: "blog-flicky-chicky-game___id"
  }, {
    path: "/id/blog/foldable-smartphones",
    component: _77d0c87a,
    name: "blog-foldable-smartphones___id"
  }, {
    path: "/id/blog/fund-raising-record-keeping",
    component: _73276188,
    name: "blog-fund-raising-record-keeping___id"
  }, {
    path: "/id/blog/remote-control-for-sony-tv",
    component: _c545fc5c,
    name: "blog-remote-control-for-sony-tv___id"
  }, {
    path: "/id/blog/remote-for-vizio-tv-ios",
    component: _ed415270,
    name: "blog-remote-for-vizio-tv-ios___id"
  }, {
    path: "/id/blog/scam-secure-camera",
    component: _0f0e2175,
    name: "blog-scam-secure-camera___id"
  }, {
    path: "/id/blog/smart-tvs-remote-control-for-ios-android",
    component: _53e4afcb,
    name: "blog-smart-tvs-remote-control-for-ios-android___id"
  }, {
    path: "/id/blog/universal-remote-control-for-ruko-devices",
    component: _017e2276,
    name: "blog-universal-remote-control-for-ruko-devices___id"
  }, {
    path: "/id/blog/universal-remote-for-lg-ios",
    component: _03fd291e,
    name: "blog-universal-remote-for-lg-ios___id"
  }, {
    path: "/id/blog/universal-tv-remote-control",
    component: _6fdb5936,
    name: "blog-universal-tv-remote-control___id"
  }, {
    path: "/id/category/cyber-security",
    component: _cdaf3c62,
    name: "category-cyber-security___id"
  }, {
    path: "/id/category/games",
    component: _76f9a3d0,
    name: "category-games___id"
  }, {
    path: "/id/category/mobile-apps",
    component: _c84c01d8,
    name: "category-mobile-apps___id"
  }, {
    path: "/id/category/smartphones",
    component: _7c42bf63,
    name: "category-smartphones___id"
  }, {
    path: "/id/category/social",
    component: _9d624014,
    name: "category-social___id"
  }, {
    path: "/id/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___id"
  }, {
    path: "/id/collection/products",
    component: _11441b23,
    name: "collection-products___id"
  }, {
    path: "/id/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___id"
  }, {
    path: "/id/mobile-apps/remote-control-for-roku-devices",
    component: _66dc84a8,
    name: "mobile-apps-remote-control-for-roku-devices___id"
  }, {
    path: "/id/portfolio/auto-silence-at-prayers-time",
    component: _e5f337e6,
    name: "portfolio-auto-silence-at-prayers-time___id"
  }, {
    path: "/id/portfolio/codematics-lg-remote-control",
    component: _bb991bec,
    name: "portfolio-codematics-lg-remote-control___id"
  }, {
    path: "/id/portfolio/flash-on-call-and-sms",
    component: _67384524,
    name: "portfolio-flash-on-call-and-sms___id"
  }, {
    path: "/id/portfolio/guess-the-word-multiplayer",
    component: _478eea3c,
    name: "portfolio-guess-the-word-multiplayer___id"
  }, {
    path: "/id/portfolio/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _b68b132e,
    name: "portfolio-kardaan-handyman-services-at-your-door-stepearly-access___id"
  }, {
    path: "/id/portfolio/scam",
    component: _509c1f22,
    name: "portfolio-scam___id"
  }, {
    path: "/id/portfolio/smart-tvs-remote-control-for-ios-and-android",
    component: _41264acd,
    name: "portfolio-smart-tvs-remote-control-for-ios-and-android___id"
  }, {
    path: "/id/portfolio/snap-war",
    component: _204d7866,
    name: "portfolio-snap-war___id"
  }, {
    path: "/id/portfolio/sonybravia-android-tv-remote-control",
    component: _0b4e8ed1,
    name: "portfolio-sonybravia-android-tv-remote-control___id"
  }, {
    path: "/id/portfolio/the-blood-community-app",
    component: _3181f2bb,
    name: "portfolio-the-blood-community-app___id"
  }, {
    path: "/id/portfolio/universal-tv-remote-control",
    component: _4a2c546a,
    name: "portfolio-universal-tv-remote-control___id"
  }, {
    path: "/id/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___id"
  }, {
    path: "/id/utils/faq",
    component: _587e7066,
    name: "utils-faq___id"
  }, {
    path: "/id/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___id"
  }, {
    path: "/id/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___id"
  }, {
    path: "/pt/about/team",
    component: _a88890ce,
    name: "about-team___pt"
  }, {
    path: "/pt/blog/blood-community-pakistan",
    component: _17fb0a2b,
    name: "blog-blood-community-pakistan___pt"
  }, {
    path: "/pt/blog/blood-donation",
    component: _ceaf288c,
    name: "blog-blood-donation___pt"
  }, {
    path: "/pt/blog/bomb-diffuse",
    component: _a7b2d6f0,
    name: "blog-bomb-diffuse___pt"
  }, {
    path: "/pt/blog/bomber-warrior",
    component: _3e6b1fca,
    name: "blog-bomber-warrior___pt"
  }, {
    path: "/pt/blog/cv-builder-app",
    component: _424dad2a,
    name: "blog-cv-builder-app___pt"
  }, {
    path: "/pt/blog/data-privacy",
    component: _9d424acc,
    name: "blog-data-privacy___pt"
  }, {
    path: "/pt/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___pt"
  }, {
    path: "/pt/blog/flicky-chicky-game",
    component: _033547a8,
    name: "blog-flicky-chicky-game___pt"
  }, {
    path: "/pt/blog/foldable-smartphones",
    component: _77d0c87a,
    name: "blog-foldable-smartphones___pt"
  }, {
    path: "/pt/blog/fund-raising-record-keeping",
    component: _73276188,
    name: "blog-fund-raising-record-keeping___pt"
  }, {
    path: "/pt/blog/remote-control-for-sony-tv",
    component: _c545fc5c,
    name: "blog-remote-control-for-sony-tv___pt"
  }, {
    path: "/pt/blog/remote-for-vizio-tv-ios",
    component: _ed415270,
    name: "blog-remote-for-vizio-tv-ios___pt"
  }, {
    path: "/pt/blog/scam-secure-camera",
    component: _0f0e2175,
    name: "blog-scam-secure-camera___pt"
  }, {
    path: "/pt/blog/smart-tvs-remote-control-for-ios-android",
    component: _53e4afcb,
    name: "blog-smart-tvs-remote-control-for-ios-android___pt"
  }, {
    path: "/pt/blog/universal-remote-control-for-ruko-devices",
    component: _017e2276,
    name: "blog-universal-remote-control-for-ruko-devices___pt"
  }, {
    path: "/pt/blog/universal-remote-for-lg-ios",
    component: _03fd291e,
    name: "blog-universal-remote-for-lg-ios___pt"
  }, {
    path: "/pt/blog/universal-tv-remote-control",
    component: _6fdb5936,
    name: "blog-universal-tv-remote-control___pt"
  }, {
    path: "/pt/category/cyber-security",
    component: _cdaf3c62,
    name: "category-cyber-security___pt"
  }, {
    path: "/pt/category/games",
    component: _76f9a3d0,
    name: "category-games___pt"
  }, {
    path: "/pt/category/mobile-apps",
    component: _c84c01d8,
    name: "category-mobile-apps___pt"
  }, {
    path: "/pt/category/smartphones",
    component: _7c42bf63,
    name: "category-smartphones___pt"
  }, {
    path: "/pt/category/social",
    component: _9d624014,
    name: "category-social___pt"
  }, {
    path: "/pt/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___pt"
  }, {
    path: "/pt/collection/products",
    component: _11441b23,
    name: "collection-products___pt"
  }, {
    path: "/pt/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___pt"
  }, {
    path: "/pt/mobile-apps/remote-control-for-roku-devices",
    component: _66dc84a8,
    name: "mobile-apps-remote-control-for-roku-devices___pt"
  }, {
    path: "/pt/portfolio/auto-silence-at-prayers-time",
    component: _e5f337e6,
    name: "portfolio-auto-silence-at-prayers-time___pt"
  }, {
    path: "/pt/portfolio/codematics-lg-remote-control",
    component: _bb991bec,
    name: "portfolio-codematics-lg-remote-control___pt"
  }, {
    path: "/pt/portfolio/flash-on-call-and-sms",
    component: _67384524,
    name: "portfolio-flash-on-call-and-sms___pt"
  }, {
    path: "/pt/portfolio/guess-the-word-multiplayer",
    component: _478eea3c,
    name: "portfolio-guess-the-word-multiplayer___pt"
  }, {
    path: "/pt/portfolio/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _b68b132e,
    name: "portfolio-kardaan-handyman-services-at-your-door-stepearly-access___pt"
  }, {
    path: "/pt/portfolio/scam",
    component: _509c1f22,
    name: "portfolio-scam___pt"
  }, {
    path: "/pt/portfolio/smart-tvs-remote-control-for-ios-and-android",
    component: _41264acd,
    name: "portfolio-smart-tvs-remote-control-for-ios-and-android___pt"
  }, {
    path: "/pt/portfolio/snap-war",
    component: _204d7866,
    name: "portfolio-snap-war___pt"
  }, {
    path: "/pt/portfolio/sonybravia-android-tv-remote-control",
    component: _0b4e8ed1,
    name: "portfolio-sonybravia-android-tv-remote-control___pt"
  }, {
    path: "/pt/portfolio/the-blood-community-app",
    component: _3181f2bb,
    name: "portfolio-the-blood-community-app___pt"
  }, {
    path: "/pt/portfolio/universal-tv-remote-control",
    component: _4a2c546a,
    name: "portfolio-universal-tv-remote-control___pt"
  }, {
    path: "/pt/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___pt"
  }, {
    path: "/pt/utils/faq",
    component: _587e7066,
    name: "utils-faq___pt"
  }, {
    path: "/pt/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___pt"
  }, {
    path: "/pt/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___pt"
  }, {
    path: "/zh/about/team",
    component: _a88890ce,
    name: "about-team___zh"
  }, {
    path: "/zh/blog/blood-community-pakistan",
    component: _17fb0a2b,
    name: "blog-blood-community-pakistan___zh"
  }, {
    path: "/zh/blog/blood-donation",
    component: _ceaf288c,
    name: "blog-blood-donation___zh"
  }, {
    path: "/zh/blog/bomb-diffuse",
    component: _a7b2d6f0,
    name: "blog-bomb-diffuse___zh"
  }, {
    path: "/zh/blog/bomber-warrior",
    component: _3e6b1fca,
    name: "blog-bomber-warrior___zh"
  }, {
    path: "/zh/blog/cv-builder-app",
    component: _424dad2a,
    name: "blog-cv-builder-app___zh"
  }, {
    path: "/zh/blog/data-privacy",
    component: _9d424acc,
    name: "blog-data-privacy___zh"
  }, {
    path: "/zh/blog/detail-blog",
    component: _49723d6b,
    name: "blog-detail-blog___zh"
  }, {
    path: "/zh/blog/flicky-chicky-game",
    component: _033547a8,
    name: "blog-flicky-chicky-game___zh"
  }, {
    path: "/zh/blog/foldable-smartphones",
    component: _77d0c87a,
    name: "blog-foldable-smartphones___zh"
  }, {
    path: "/zh/blog/fund-raising-record-keeping",
    component: _73276188,
    name: "blog-fund-raising-record-keeping___zh"
  }, {
    path: "/zh/blog/remote-control-for-sony-tv",
    component: _c545fc5c,
    name: "blog-remote-control-for-sony-tv___zh"
  }, {
    path: "/zh/blog/remote-for-vizio-tv-ios",
    component: _ed415270,
    name: "blog-remote-for-vizio-tv-ios___zh"
  }, {
    path: "/zh/blog/scam-secure-camera",
    component: _0f0e2175,
    name: "blog-scam-secure-camera___zh"
  }, {
    path: "/zh/blog/smart-tvs-remote-control-for-ios-android",
    component: _53e4afcb,
    name: "blog-smart-tvs-remote-control-for-ios-android___zh"
  }, {
    path: "/zh/blog/universal-remote-control-for-ruko-devices",
    component: _017e2276,
    name: "blog-universal-remote-control-for-ruko-devices___zh"
  }, {
    path: "/zh/blog/universal-remote-for-lg-ios",
    component: _03fd291e,
    name: "blog-universal-remote-for-lg-ios___zh"
  }, {
    path: "/zh/blog/universal-tv-remote-control",
    component: _6fdb5936,
    name: "blog-universal-tv-remote-control___zh"
  }, {
    path: "/zh/category/cyber-security",
    component: _cdaf3c62,
    name: "category-cyber-security___zh"
  }, {
    path: "/zh/category/games",
    component: _76f9a3d0,
    name: "category-games___zh"
  }, {
    path: "/zh/category/mobile-apps",
    component: _c84c01d8,
    name: "category-mobile-apps___zh"
  }, {
    path: "/zh/category/smartphones",
    component: _7c42bf63,
    name: "category-smartphones___zh"
  }, {
    path: "/zh/category/social",
    component: _9d624014,
    name: "category-social___zh"
  }, {
    path: "/zh/collection/detail-product",
    component: _758cd872,
    name: "collection-detail-product___zh"
  }, {
    path: "/zh/collection/products",
    component: _11441b23,
    name: "collection-products___zh"
  }, {
    path: "/zh/contact/with-map",
    component: _5cd768a4,
    name: "contact-with-map___zh"
  }, {
    path: "/zh/mobile-apps/remote-control-for-roku-devices",
    component: _66dc84a8,
    name: "mobile-apps-remote-control-for-roku-devices___zh"
  }, {
    path: "/zh/portfolio/auto-silence-at-prayers-time",
    component: _e5f337e6,
    name: "portfolio-auto-silence-at-prayers-time___zh"
  }, {
    path: "/zh/portfolio/codematics-lg-remote-control",
    component: _bb991bec,
    name: "portfolio-codematics-lg-remote-control___zh"
  }, {
    path: "/zh/portfolio/flash-on-call-and-sms",
    component: _67384524,
    name: "portfolio-flash-on-call-and-sms___zh"
  }, {
    path: "/zh/portfolio/guess-the-word-multiplayer",
    component: _478eea3c,
    name: "portfolio-guess-the-word-multiplayer___zh"
  }, {
    path: "/zh/portfolio/kardaan-handyman-services-at-your-door-stepearly-access",
    component: _b68b132e,
    name: "portfolio-kardaan-handyman-services-at-your-door-stepearly-access___zh"
  }, {
    path: "/zh/portfolio/scam",
    component: _509c1f22,
    name: "portfolio-scam___zh"
  }, {
    path: "/zh/portfolio/smart-tvs-remote-control-for-ios-and-android",
    component: _41264acd,
    name: "portfolio-smart-tvs-remote-control-for-ios-and-android___zh"
  }, {
    path: "/zh/portfolio/snap-war",
    component: _204d7866,
    name: "portfolio-snap-war___zh"
  }, {
    path: "/zh/portfolio/sonybravia-android-tv-remote-control",
    component: _0b4e8ed1,
    name: "portfolio-sonybravia-android-tv-remote-control___zh"
  }, {
    path: "/zh/portfolio/the-blood-community-app",
    component: _3181f2bb,
    name: "portfolio-the-blood-community-app___zh"
  }, {
    path: "/zh/portfolio/universal-tv-remote-control",
    component: _4a2c546a,
    name: "portfolio-universal-tv-remote-control___zh"
  }, {
    path: "/zh/utils/coming-soon",
    component: _422df997,
    name: "utils-coming-soon___zh"
  }, {
    path: "/zh/utils/faq",
    component: _587e7066,
    name: "utils-faq___zh"
  }, {
    path: "/zh/utils/maintenance",
    component: _798059e3,
    name: "utils-maintenance___zh"
  }, {
    path: "/zh/utils/pricing",
    component: _473e1116,
    name: "utils-pricing___zh"
  }],

  fallback: false
}

export function createRouter (ssrContext, config) {
  const base = (config._app && config._app.basePath) || routerOptions.base
  const router = new Router({ ...routerOptions, base  })

  // TODO: remove in Nuxt 3
  const originalPush = router.push
  router.push = function push (location, onComplete = emptyFn, onAbort) {
    return originalPush.call(this, location, onComplete, onAbort)
  }

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    return resolve(to, current, append)
  }

  return router
}
